### ISSUE TITLE
Failure to install plist file

### ISSUE THREAD

**Issue by miccheng** [riboseinc/homebrew-jenkins-slave#1]
I get this error: 

```
Updating Homebrew...
==> Installing jenkins-slave from riboseinc/jenkins-slave
==> Downloading http://repo.jenkins-ci.org/releases/org/jenkins-ci/main/remoting/3.14/remoting-3.14.jar
######################################################################## 100.0%
Error: Failed to install plist file
Error: undefined method `undent' for #<String:0x00000001015997f8>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/riboseinc/homebrew-jenkins-slave/jenkins-slave.rb:85:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:613:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:664:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:330:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:257:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:257:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

Specifically:

> Error: undefined method `undent'

**Comment by miccheng** [comment]
w00t! Thanks @ronaldtse !
